# Generated by Django 5.2 on 2025-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_remove_answersheet_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='dummy_field',
            field=models.BooleanField(default=True),
        ),
    ]
