# Generated by Django 5.2 on 2025-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_paper_dummy_field_paper_paper_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paper_date',
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_year',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
