# Generated by Django 5.2 on 2025-05-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_paper_paper_date_paper_paper_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_number',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_year',
        ),
        migrations.AddField(
            model_name='paper',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='exam.papername'),
        ),
    ]
