# Generated by Django 5.2 on 2025-05-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_papername_remove_paper_paper_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='paper_time',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
