# Generated by Django 5.2 on 2025-05-27 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_remove_paper_paper_time_useranswer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionandoptions',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_questions', to='exam.paper'),
        ),
        migrations.CreateModel(
            name='QuestionAndNumerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numerical_questions', to='exam.paper')),
            ],
        ),
    ]
