# Generated by Django 5.2 on 2025-05-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exam', '0009_alter_questionandoptions_paper_questionandnumerical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionandoptions',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='chemistryQuestionAndNumerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_numerical_questions', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='chemistryQuestionAndOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemistry_mcq_questions', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='mathsQuestionAndNumerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_numerical_questions', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='mathsQuestionAndOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maths_mcq_questions', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='physicsQuestionAndNumerical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physics_numerical_questions', to='exam.paper')),
            ],
        ),
        migrations.CreateModel(
            name='physicsQuestionAndOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physics_mcq_questions', to='exam.paper')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionAndNumerical',
        ),
        migrations.DeleteModel(
            name='QuestionAndOptions',
        ),
    ]
