# Generated by Django 5.2 on 2025-05-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_paper_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='month',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='year',
        ),
        migrations.AddField(
            model_name='paper',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
