# Generated by Django 5.2 on 2025-05-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_remove_paper_month_remove_paper_year_paper_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='date',
        ),
        migrations.AddField(
            model_name='paper',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
