# Generated by Django 5.2 on 2025-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_remove_paper_date_paper_month_paper_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
