# Generated by Django 5.2 on 2025-05-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_paper_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='month',
            field=models.CharField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], max_length=20, null=True),
        ),
    ]
