# Generated by Django 5.2 on 2025-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_paper_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
