# Generated by Django 5.2.3 on 2025-06-11 07:35

import exam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_alter_paper_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistryquestionandnumerical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.question_image_upload_path),
        ),
        migrations.AddField(
            model_name='chemistryquestionandnumerical',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chemistryquestionandoptions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.question_image_upload_path),
        ),
        migrations.AddField(
            model_name='chemistryquestionandoptions',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mathsquestionandnumerical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.question_image_upload_path),
        ),
        migrations.AddField(
            model_name='mathsquestionandnumerical',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mathsquestionandoptions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.question_image_upload_path),
        ),
        migrations.AddField(
            model_name='mathsquestionandoptions',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicsquestionandnumerical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.question_image_upload_path),
        ),
        migrations.AddField(
            model_name='physicsquestionandnumerical',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='physicsquestionandoptions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=exam.models.question_image_upload_path),
        ),
        migrations.AddField(
            model_name='physicsquestionandoptions',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
