# Generated by Django 5.2.3 on 2025-06-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_chemistryquestionandnumerical_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_id',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey> (<django.db.models.fields.PositiveIntegerField>-<django.db.models.fields.CharField>)-day-<django.db.models.fields.PositiveSmallIntegerField>- Shift <django.db.models.fields.IntegerField>'),
        ),
    ]
