# Generated by Django 5.2.3 on 2025-06-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
